import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import { CharactersCard } from "../components/characters-card";
import styles from "../styles/Home.module.css";
import { instance } from "../utlis";

export default function Home(props) {
  const [data, setData] = useState([]);
  const [info, setInfo] = useState();
  const [page, setPage] = useState(1);
  const [searchValue, setSearchValue] = useState("");

  useEffect(() => {
    const fetchData = async () => {
      const res = await fetch(`https://rickandmortyapi.com/api/character/?page=${page}`);
      const data = await res.json();
      setData((prev) => [...prev, ...data.results]);
      setInfo(data.info);
    };
    fetchData();
  }, [page]);

  useEffect(() => {
    const fetchData = async () => {
      const res = await fetch(`https://rickandmortyapi.com/api/character/?name=${searchValue}`);
      const data = await res.json();
      setData(data.results);
      setInfo(data.info);
    };
    fetchData();
  }, [searchValue]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <input
        value={searchValue}
        onChange={(e) => setSearchValue(e.target.value)}
      />
      <main className={styles.main}>
        {data?.map((character) => (
          <Link href={`/characters/${character.id}`} key={character.id}>
            <CharactersCard
              name={character.name}
              species={character.species}
              image={character.image}
            />
          </Link>
        ))}
        {info?.next && (
          <button onClick={() => setPage((prev) => prev + 1)}>LOAD MORE</button>
        )}
      </main>
    </>
  );
}

export async function getServerSideProps(ctx) {
  const data = await instance({
    url: 'character',
    params: ctx.query,
  });
  return { props: data.data };
}