import { CharactersCard } from "../components/characters-card";
import Head from "next/head";
import { useEffect, useState } from "react";
import { LocationsContext } from "../store";
import { instance } from "../utlis";
import { LoadMoreButton, LocationsList } from "../components";

export default function Locations() {
  const [state, setState] = useState([]);
  const [info, setInfo] = useState();
  const [page, setPage] = useState(1);

  useEffect(() => {
    instance({
      url: "location",
      params: {
        page,
      },
    }).then((res) => {
      setState(res.data.results);
      setInfo(res.data.info);
    });
  }, [page]);

  return (
    <LocationsContext.Provider value={{
      locations: state,
      info,
      setPage: setPage,
    }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <LocationsList />
        <LoadMoreButton />
      </main>
    </LocationsContext.Provider>
  );
}
