import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";

export default function EpisodeProfile() {
  const router = useRouter();
  const [data, setData] = useState({});

  useEffect(() => {
    router.query.pid &&
    fetch(`https://rickandmortyapi.com/api/episode/${router.query.pid}`)
      .then((res) => res.json())
      .then(async (res) => {
        if (res.characters?.length) {
          await fetch(
            `https://rickandmortyapi.com/api/character/${res.characters
                .map((characters) => characters.split("/").pop())
                .join(",")}`
          )
            .then((res) => res.json())
            .then((characters) => (res.characters = characters));
        }

        return res;
      })
      .then((res) => setData(res));
  }, [router.query]);


  return (
    <>
      <Head>
        <title>{data.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ display: "flex", flexDirection: "column"}}>
        <h1>{data.name}</h1>
        <div style={{ display: "grid", gridColumn: 2, gap: "50px" }}>
          <div style={{ display: "flex", flexDirection: "column"}}>
            <h2>Characters</h2>
          </div>
            {data.characters?.map((characters) => (
              <Link key={characters.id} href={`/characters/${characters.id}`}>
                  <div>
                    <img src={characters.image}/>
                    <h4>{characters.name}</h4>
                  </div>
              </Link>
            ))}
          </div>
      </main>
    </>
  );
}